# Generated by Django 5.2.11 on 2026-02-18 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='next_game_date',
            field=models.DateField(blank=True, help_text='Date of the next game session.', null=True),
        ),
    ]
