# Generated by Django 5.2.11 on 2026-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0003_sitesettings_charter_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='PullingString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('cost', models.IntegerField(default=0, help_text='XP cost to acquire.')),
                ('category', models.CharField(choices=[('general', 'General'), ('fixer', 'Fixer'), ('soldier', 'Soldier'), ('science', 'Science'), ('engineer', 'Engineer'), ('ai', 'AI')], default='general', max_length=20)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
