# Generated by Django 5.2.11 on 2026-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0005_seed_pulling_strings'),
    ]

    operations = [
        migrations.AddField(
            model_name='pullingstring',
            name='is_linkable',
            field=models.BooleanField(default=False, help_text='If true, each instance can be linked to an NPC dossier. Can be taken multiple times.'),
        ),
    ]
