# Generated by Django 5.2.11 on 2026-03-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0007_personal_npc_linkable'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeritDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('cost', models.IntegerField(default=1, help_text='Dot cost. For variable merits (e.g. 1-5), store the max rating.')),
                ('min_cost', models.IntegerField(default=1, help_text='Minimum dot rating. Set equal to cost for fixed-cost merits.')),
                ('category', models.CharField(choices=[('physical', 'Physical'), ('mental', 'Mental'), ('social', 'Social'), ('supernatural', 'Supernatural')], default='physical', max_length=20)),
                ('prerequisites', models.CharField(blank=True, default='', help_text="Human-readable prerequisites (e.g. 'Stamina 4+').", max_length=200)),
                ('effects', models.JSONField(blank=True, default=dict, help_text='Mechanical effects as JSON. Keys: extra_health (int), size_mod (int), stat_bonus ({stat: bonus}), skill_bonus ({skill: bonus}), difficulty_mod ({context: mod}), willpower_mod (int), speed_mod (int), custom (str description of non-standard effect).')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
