# Generated by Django 5.2.11 on 2026-03-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0008_meritdefinition'),
    ]

    operations = [
        migrations.AddField(
            model_name='meritdefinition',
            name='class_restriction',
            field=models.CharField(blank=True, choices=[('', 'All Classes'), ('fixer', 'Fixer'), ('soldier', 'Soldier'), ('science', 'Science'), ('engineer', 'Engineer'), ('ai', 'AI')], default='', help_text='If set, only characters of this class can take this merit. Blank = available to all.', max_length=20),
        ),
    ]
