# Generated by Django 5.2.11 on 2026-04-06 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0009_meritdefinition_class_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='lock_comms',
            field=models.BooleanField(default=True, help_text='Lock comms and cyber terminal for non-superusers (unlock during game sessions).'),
        ),
    ]
