# Generated by Django 5.2.11 on 2026-04-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0010_sitesettings_lock_comms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_star_map',
            field=models.BooleanField(default=False, help_text='Show STAR MAP link in navigation for all players.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_world_map',
            field=models.BooleanField(default=True, help_text='Show WORLD MAP link in navigation for all players.'),
        ),
    ]
