# Generated by Django 5.2.11 on 2026-04-11 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0011_sitesettings_show_star_map_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='council_mode',
            field=models.CharField(default='agency', help_text="Council voting mode: 'agency' (agencies vote) or 'player' (individual players/NPCs vote).", max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='label_agencies',
            field=models.CharField(blank=True, default='AGENCIES', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='label_comms',
            field=models.CharField(blank=True, default='COMMS', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='label_council',
            field=models.CharField(blank=True, default='COUNCIL', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='label_dispatch',
            field=models.CharField(blank=True, default='DISPATCH', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='label_npcs',
            field=models.CharField(blank=True, default="NPC'S", max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='label_players',
            field=models.CharField(blank=True, default='PLAYERS', max_length=50),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_council',
            field=models.BooleanField(default=True, help_text='Show COUNCIL link in navigation.'),
        ),
    ]
