# Generated by Django 5.2.11 on 2026-06-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0021_sitesettings_combat_npcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_exotic_matter',
            field=models.BooleanField(default=False, help_text='Show Exotic Matter in star-map system resource readouts. Enable once players can detect exotic matter.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_ftl_route_planning',
            field=models.BooleanField(default=False, help_text='Show the FTL ROUTE PLANNING panel on the star map. Enable once players invent FTL route planning.'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='weapons',
            field=models.JSONField(blank=True, default=list, help_text="List of weapon-entry dicts. Per-entry keys: name (str), category (str: melee | improvised | firearm | thrown), damage (str: e.g. '2L'), range (str), capacity (str), notes (str). For firearms, an optional auto_capable (bool) flag controls whether burst-fire / autofire-spread modes are offered on the attack form (legacy entries without the flag default to False at read time). For firearms, an optional magazine (int) field defines the catalogue magazine size in rounds (legacy entries without the field default to 0 at read time, which suppresses ammo tracking for that weapon). For firearms, an optional again (int: 8 / 9 / 10, default 10) sets the X-again explosion threshold for the attack roll — 10-again (default) re-rolls on 10, 9-again re-rolls on 9 or 10, 8-again re-rolls on 8/9/10. The success threshold (8+) does NOT change between tiers — only the explosion trigger does. For firearms, an optional close_range_penalty (int, default 0; clamped ±10 via _clamp_close_range_penalty) subtracts from the attack pool when the resolved range_band is 'close' — long-barrel rifles (DMR, Scoped Rifle) are unwieldy in CQB and seed with negative values (DMR -2, Scoped Rifle -3). See SiteSettings.default_weapons() for the seed catalogue."),
        ),
    ]
