# Generated by Django 5.2.11 on 2026-06-20 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0022_sitesettings_show_exotic_matter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='jump_economy_config',
            field=models.JSONField(blank=True, default=dict, help_text='Tunable FTL-jump economy coefficients (see default_jump_economy()).'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_ftl_jumps',
            field=models.BooleanField(default=False, help_text='Enable FTL jumps: ships move between systems via a costed jump action that spends hull condition. Enable once players have FTL travel.'),
        ),
    ]
