# Generated by Django 5.2.11 on 2026-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0023_sitesettings_jump_economy_config_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='scanning_turn_number',
            field=models.IntegerField(default=0, help_text='Increments each time the GM opens a scanning turn; the per-observatory once-only key.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='scanning_turn_open',
            field=models.BooleanField(default=False, help_text='When open, agencies may scan discovered systems (one per observatory). GM opens/closes turns.'),
        ),
    ]
