# Generated by Django 5.2.11 on 2026-06-24 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0024_sitesettings_scanning_turn_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='show_public_star_map',
            field=models.BooleanField(default=False, help_text='Show the read-only PUBLIC MAP link in navigation for all players (shared public star-intel record, no jump routes).'),
        ),
    ]
