# Generated by Django 5.2.11 on 2026-04-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='game_date',
            field=models.CharField(blank=True, default='', help_text="In-game date displayed on the article (e.g. '9 February 2036, Evening')", max_length=100),
        ),
    ]
