# Generated by Django 5.2.11 on 2026-04-05 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsarticle_game_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsarticle',
            options={'ordering': ['-game_date_sort', '-created_at']},
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='game_date_sort',
            field=models.DateTimeField(blank=True, help_text='Sortable in-game datetime for ordering articles chronologically', null=True),
        ),
    ]
