# Generated by Django 5.2.11 on 2026-04-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsarticle_options_newsarticle_game_date_sort'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='featured_image_full',
            field=models.BooleanField(default=False, help_text='Show full image instead of cropping to fit'),
        ),
    ]
