# Generated by Django 5.2.11 on 2026-04-06 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_newsarticle_featured_image_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='released_at',
            field=models.DateTimeField(blank=True, help_text='When the eyes-only article was released to all players', null=True),
        ),
    ]
