# Generated by Django 5.2.11 on 2026-04-07 10:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsarticle_released_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='shared_with',
            field=models.ManyToManyField(blank=True, help_text='Additional players who can see this eyes-only article', related_name='shared_news', to=settings.AUTH_USER_MODEL),
        ),
    ]
