# Generated by Django 5.2.11 on 2026-06-20 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0035_add_section_versioning'),
        ('starships', '0010_battery_tier'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumpLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('jump', 'Jump'), ('resupply', 'Resupply'), ('gm_adjust', 'GM Adjust')], default='jump', max_length=20)),
                ('from_system_name', models.CharField(blank=True, default='', max_length=200)),
                ('to_system_name', models.CharField(blank=True, default='', max_length=200)),
                ('distance_ly', models.FloatField(default=0)),
                ('maintenance_basis', models.IntegerField(default=0, help_text='Class maintenance value at action time (cost basis).')),
                ('wear', models.IntegerField(default=0, help_text='Condition % lost (jump) or restored (resupply, negative).')),
                ('costs', models.JSONField(blank=True, default=dict, help_text='Per-resource spend {resource_key: qty}. Empty in Phase 1.')),
                ('reason', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jump_logs', to='agencies.agency')),
                ('ship', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jump_logs', to='starships.starship')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
