# Generated by Django 5.2.11 on 2026-06-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starships', '0011_jumplog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumplog',
            name='kind',
            field=models.CharField(choices=[('jump', 'Jump'), ('resupply', 'Resupply'), ('extract', 'Extract'), ('gm_adjust', 'GM Adjust')], default='jump', max_length=20),
        ),
    ]
