# Generated by Django 5.2.11 on 2026-02-12 17:56

import characters.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='UNKNOWN AGENT', max_length=200)),
                ('concept', models.CharField(blank=True, default='', max_length=200)),
                ('chronicle', models.CharField(blank=True, default='', max_length=200)),
                ('virtue', models.CharField(blank=True, default='', max_length=100)),
                ('vice', models.CharField(blank=True, default='', max_length=100)),
                ('attributes', models.JSONField(default=characters.models.default_attributes)),
                ('skills', models.JSONField(default=characters.models.default_skills)),
                ('health_bashing', models.IntegerField(default=0)),
                ('health_lethal', models.IntegerField(default=0)),
                ('health_aggravated', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=5)),
                ('merits', models.JSONField(default=list)),
                ('flaws', models.JSONField(default=list)),
                ('pulling_strings', models.JSONField(default=list)),
                ('inventory', models.JSONField(default=list)),
                ('experience', models.IntegerField(default=0)),
                ('willpower_current', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
