# Generated by Django 5.2.11 on 2026-02-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='mental_load',
            field=models.IntegerField(default=0),
        ),
    ]
