# Generated by Django 5.2.11 on 2026-02-17 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0002_character_mental_load'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dossier',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='character',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='character_portraits/'),
        ),
    ]
