# Generated by Django 5.2.11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0003_character_dossier_character_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='specialisations',
            field=models.JSONField(default=list),
        ),
    ]
