# Generated by Django 5.2.11 on 2026-03-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_character_specialisations'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='experience_used',
            field=models.IntegerField(default=0),
        ),
    ]
