# Generated by Django 5.2.11 on 2026-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_character_experience_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='character_class',
            field=models.CharField(blank=True, choices=[('fixer', 'Fixer'), ('soldier', 'Soldier'), ('science', 'Science'), ('engineer', 'Engineer'), ('ai', 'AI')], default='', max_length=20),
        ),
    ]
