# Generated by Django 5.2.11 on 2026-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_character_character_class'),
        ('exodus', '0004_pullingstring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='pulling_strings',
        ),
        migrations.AddField(
            model_name='character',
            name='pulling_strings',
            field=models.ManyToManyField(blank=True, related_name='characters', to='exodus.pullingstring'),
        ),
    ]
