# Generated by Django 5.2.11 on 2026-03-25 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0008_pulling_strings_through_table'),
        ('exodus', '0008_meritdefinition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='merits',
            field=models.JSONField(db_column='merits', default=list),
        ),
        migrations.RenameField(
            model_name='character',
            old_name='merits',
            new_name='merits_old',
        ),
        migrations.AlterField(
            model_name='characterpullingstring',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='CharacterMerit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1, help_text="Chosen dot rating (between merit's min_cost and cost).")),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='character_merits', to='characters.character')),
                ('merit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exodus.meritdefinition')),
            ],
            options={
                'ordering': ['merit__category', 'merit__name'],
            },
        ),
        migrations.AddField(
            model_name='character',
            name='merit_entries',
            field=models.ManyToManyField(blank=True, through='characters.CharacterMerit', to='exodus.meritdefinition'),
        ),
    ]
