# Generated by Django 5.2.11 on 2026-03-25 19:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0016_agency_map_color_base_coordinates'),
        ('characters', '0009_alter_character_merits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='XpTransferLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(help_text='Character XP spent.')),
                ('agency_received', models.IntegerField(help_text='Agency XP gained.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transfers', to='agencies.agency')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xp_transfers', to='characters.character')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
