# Generated by Django 5.2.11 on 2026-03-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0010_xptransferlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='classified_notes',
            field=models.TextField(blank=True, default='', help_text='Private notes visible only to the player and GM.'),
        ),
    ]
