# Generated by Django 5.2.11 on 2026-04-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0011_character_classified_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='merit_uses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
