# Generated by Django 5.2.11 on 2026-06-22 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0038_agency_scan_grant_agency_scan_usage_and_more'),
        ('characters', '0012_add_merit_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='Agency this sub-character belongs to (informational).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_characters', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='character',
            name='is_sub_character',
            field=models.BooleanField(default=False, help_text='Soldier/tactical sub-unit. Excluded from the agency XP economy.'),
        ),
    ]
