# Generated by Django 5.2.11 on 2026-06-28 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_seed_bifrost_sub_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='creation_mode',
            field=models.BooleanField(default=False, help_text='Free-build mode: bypass XP enforcement on the sheet so dots can be added/removed freely during character creation.'),
        ),
    ]
