# Generated by Django 5.2.11 on 2026-02-17 09:24

import agencies.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('alliance', models.CharField(blank=True, default='', max_length=200)),
                ('motto', models.CharField(blank=True, default='', max_length=200)),
                ('headquarters', models.CharField(blank=True, default='', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('integrity', models.IntegerField(default=0)),
                ('experience', models.IntegerField(default=0)),
                ('is_player_agency', models.BooleanField(default=False)),
                ('attributes', models.JSONField(default=agencies.models.default_agency_attributes)),
                ('specializations', models.JSONField(default=list)),
                ('merits', models.JSONField(default=list)),
                ('flaws', models.JSONField(default=list)),
                ('assets', models.JSONField(default=list)),
                ('fleet', models.JSONField(default=list)),
                ('conditions', models.JSONField(default=list)),
                ('projects', models.JSONField(default=list)),
                ('history', models.JSONField(default=list)),
                ('field_visibility', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'agencies',
                'ordering': ['-is_player_agency', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('proposed_changes', models.JSONField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_requests', to='agencies.agency')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_change_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
