# Generated by Django 5.2.11 on 2026-02-17 09:58

import agencies.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='alliance',
            field=models.JSONField(default=agencies.models.default_alliance),
        ),
    ]
