# Generated by Django 5.2.11 on 2026-03-15 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0003_globalflaw'),
    ]

    operations = [
        migrations.CreateModel(
            name='FTLProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('pros', models.JSONField(default=list)),
                ('cons', models.JSONField(default=list)),
                ('required_successes', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AgencyFTLProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_successes', models.IntegerField(default=0)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ftl_assignments', to='agencies.agency')),
                ('ftl_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_assignments', to='agencies.ftlproject')),
            ],
            options={
                'unique_together': {('agency', 'ftl_project')},
            },
        ),
    ]
