# Generated by Django 5.2.11 on 2026-03-15 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0004_ftlproject_agencyftlproject'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('item_type', models.CharField(choices=[('agreement', 'Agreement'), ('initiative', 'Initiative'), ('law', 'Law')], default='agreement', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('active', 'Active'), ('suspended', 'Suspended'), ('repealed', 'Repealed')], default='proposed', max_length=20)),
                ('proposed_by', models.CharField(blank=True, default='', help_text='Name of the agency or entity that proposed this item.', max_length=200)),
                ('notes', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0, help_text='Lower numbers appear first.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
