# Generated by Django 5.2.11 on 2026-03-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0005_council_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='councilitem',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('voting', 'Voting'), ('active', 'Active'), ('suspended', 'Suspended'), ('repealed', 'Repealed')], default='proposed', max_length=20),
        ),
    ]
