# Generated by Django 5.2.11 on 2026-03-15 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0006_council_voting_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_council_chairman',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='agency',
            name='is_council_member',
            field=models.BooleanField(default=False),
        ),
    ]
