# Generated by Django 5.2.11 on 2026-03-19 16:16

import agencies.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_council_membership'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_types', models.JSONField(default=agencies.models.default_base_location_types)),
                ('location_merits', models.JSONField(default=agencies.models.default_base_location_merits)),
                ('facility_types', models.JSONField(default=agencies.models.default_base_facility_types)),
                ('equipment_types', models.JSONField(default=agencies.models.default_base_equipment_types)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Base Configuration',
            },
        ),
        migrations.CreateModel(
            name='Base',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NEW BASE', max_length=200)),
                ('location_type', models.CharField(blank=True, default='', max_length=100)),
                ('merits', models.JSONField(default=list)),
                ('facilities', models.JSONField(default=list)),
                ('equipment', models.JSONField(default=list)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bases', to='agencies.agency')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
