# Generated by Django 5.2.11 on 2026-03-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0008_baseconfig_base'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='workspaces',
            field=models.JSONField(default=list),
        ),
    ]
