# Generated by Django 5.2.11 on 2026-03-22 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0009_base_workspaces'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouncilVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('for', 'For'), ('against', 'Against'), ('abstain', 'Abstain')], max_length=10)),
                ('voted_at', models.DateTimeField(auto_now=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='council_votes', to='agencies.agency')),
                ('council_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='agencies.councilitem')),
            ],
            options={
                'unique_together': {('council_item', 'agency')},
            },
        ),
    ]
