# Generated by Django 5.2.11 on 2026-03-22 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0010_council_vote'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilitem',
            name='vote_record',
            field=models.JSONField(blank=True, default=dict, help_text='Frozen vote snapshot when vote concludes or is emergency suspended.'),
        ),
        migrations.AlterField(
            model_name='councilitem',
            name='status',
            field=models.CharField(choices=[('proposed', 'Proposed'), ('voting', 'Voting'), ('active', 'Active'), ('suspended', 'Suspended'), ('repealed', 'Repealed'), ('emergency_suspended', 'Emergency Suspended')], default='proposed', max_length=20),
        ),
    ]
