# Generated by Django 5.2.11 on 2026-03-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0011_council_vote_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_council_present',
            field=models.BooleanField(default=False),
        ),
    ]
