# Generated by Django 5.2.11 on 2026-03-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0017_add_engineering_science_facilities'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='zero_day_pool',
            field=models.IntegerField(default=0, help_text='Available zero-day vulnerabilities. Used by Government Zero-Day Repository pulling string.'),
        ),
    ]
