# Generated by Django 5.2.11 on 2026-03-31 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0019_classify_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition_type', models.CharField(choices=[('ransomware', 'Ransomware'), ('shutdown_power', 'Shutdown: Power Grid'), ('shutdown_water', 'Shutdown: Water Systems'), ('shutdown_logistics', 'Shutdown: Logistics Network'), ('shutdown_transport', 'Shutdown: Transport Infrastructure'), ('shutdown_media', 'Shutdown: Media Channels'), ('shutdown_comms', 'Shutdown: Communications'), ('backdoor', 'Permanent Backdoor'), ('custom', 'Custom')], default='custom', max_length=30)),
                ('description', models.CharField(max_length=500)),
                ('difficulty', models.IntegerField(default=1, help_text="Attacker's successes — difficulty to clear.")),
                ('sweep_pool', models.IntegerField(default=0, help_text='GM-allocated dice pool for Sweep & Clear.')),
                ('sweep_progress', models.IntegerField(default=0, help_text='Accumulated successes toward clearing.')),
                ('source_agency_id', models.PositiveIntegerField(blank=True, help_text='Agency that placed this condition.', null=True)),
                ('target_base_id', models.PositiveIntegerField(blank=True, help_text='Specific base affected.', null=True)),
                ('infra_type', models.CharField(blank=True, default='', help_text='Infrastructure type for shutdown conditions.', max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_conditions', to='agencies.agency')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
