# Generated by Django 5.2.11 on 2026-03-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0020_add_agency_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='sweep_pool',
            field=models.IntegerField(default=0, help_text='Shared Sweep & Clear pool — GM allocates, anyone with Computer skill can use to clear conditions.'),
        ),
    ]
