# Generated by Django 5.2.11 on 2026-03-31 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0021_add_agency_sweep_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencycondition',
            name='condition_type',
            field=models.CharField(choices=[('ransomware', 'Ransomware'), ('bad_deals', 'Fraudulent Trade Orders'), ('base_access', 'Base Systems Compromised'), ('shutdown_power', 'Shutdown: Power Grid'), ('shutdown_water', 'Shutdown: Water Systems'), ('shutdown_logistics', 'Shutdown: Logistics Network'), ('shutdown_transport', 'Shutdown: Transport Infrastructure'), ('shutdown_media', 'Shutdown: Media Channels'), ('shutdown_comms', 'Shutdown: Communications'), ('backdoor', 'Permanent Backdoor'), ('custom', 'Custom')], default='custom', max_length=30),
        ),
    ]
