# Generated by Django 5.2.11 on 2026-04-02 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0027_add_required_class_to_base_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='base',
            name='departments',
            field=models.JSONField(default=list),
        ),
    ]
