# Generated by Django 5.2.11 on 2026-04-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0029_add_fringe_lab_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='is_nuclear_power',
            field=models.BooleanField(default=False, help_text='Agency has council approval to build nuclear reactors.'),
        ),
    ]
