# Generated by Django 5.2.11 on 2026-04-07 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0030_add_is_nuclear_power'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRollLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_index', models.IntegerField(blank=True, null=True)),
                ('project_name', models.CharField(blank=True, default='', max_length=200)),
                ('character_name', models.CharField(max_length=200)),
                ('roll_type', models.CharField(max_length=20)),
                ('pool', models.IntegerField()),
                ('rolls', models.JSONField(default=list)),
                ('successes', models.IntegerField(default=0)),
                ('auto_successes', models.IntegerField(default=0)),
                ('auto_merit', models.CharField(blank=True, default='', max_length=200)),
                ('mental_damage', models.BooleanField(default=False)),
                ('old_score', models.IntegerField(default=0)),
                ('new_score', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('rolled_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_roll_logs', to='agencies.agency')),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='roll_logs', to='agencies.agencyftlproject')),
            ],
            options={
                'ordering': ['-rolled_at'],
            },
        ),
    ]
