# Generated by Django 5.2.11 on 2026-04-07 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0032_projectrolllog_add_agency_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='councilitem',
            name='predicted_votes',
            field=models.JSONField(blank=True, default=dict, help_text='GM-only predicted votes: {"agencyName": "for|against|abstain|undecided", ...}'),
        ),
    ]
