# Generated by Django 5.2.11 on 2026-06-20 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0035_add_section_versioning'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='ftl_fuel',
            field=models.IntegerField(default=0, help_text='FTL fuel stockpile. Spent on jumps; refilled by extracting fuel resources at claimed systems.'),
        ),
        migrations.AddField(
            model_name='agency',
            name='ftl_spares',
            field=models.IntegerField(default=0, help_text='FTL spares stockpile. Spent on jumps; refilled by extracting spares resources at claimed systems.'),
        ),
        migrations.AlterField(
            model_name='projectrolllog',
            name='agency',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_roll_logs', to='agencies.agency'),
        ),
    ]
