# Generated by Django 5.2.11 on 2026-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0036_agency_ftl_fuel_agency_ftl_spares_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='scan_turn_usage',
            field=models.JSONField(blank=True, default=dict, help_text='Per-turn observatory scan usage: {turnNumber: {baseId: starSystemId}}.'),
        ),
    ]
