# Generated by Django 5.2.11 on 2026-06-20 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0037_agency_scan_turn_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='scan_grant',
            field=models.IntegerField(default=0, help_text='Scans allowed per observatory (GM grant). Each observatory may scan this many times.'),
        ),
        migrations.AddField(
            model_name='agency',
            name='scan_usage',
            field=models.JSONField(blank=True, default=dict, help_text='Scans used per observatory against the current grant: {baseId: count}.'),
        ),
        migrations.AlterField(
            model_name='agency',
            name='scan_turn_usage',
            field=models.JSONField(blank=True, default=dict, help_text='Legacy per-turn observatory scan usage (vestigial).'),
        ),
    ]
