# Generated by Django 5.2.11 on 2026-03-22 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='posted_as_id',
            field=models.PositiveIntegerField(blank=True, help_text='PK of the Character or NPC being impersonated.', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='posted_as_name',
            field=models.CharField(blank=True, default='', help_text='Denormalized display name for the impersonated dossier.', max_length=200),
        ),
        migrations.AddField(
            model_name='message',
            name='posted_as_type',
            field=models.CharField(blank=True, choices=[('', 'Self'), ('character', 'Character'), ('npc', 'NPC')], default='', help_text='If set, the message is displayed as this dossier instead of the sender.', max_length=20),
        ),
    ]
