# Generated by Django 5.2.11 on 2026-03-26 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0002_add_posted_as_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comms_images/'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, default=''),
        ),
    ]
