# Generated by Django 5.2.11 on 2026-03-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0003_message_image_alter_message_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmembership',
            name='alias_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='threadmembership',
            name='alias_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='threadmembership',
            name='alias_type',
            field=models.CharField(blank=True, choices=[('', 'Self'), ('character', 'Character'), ('npc', 'NPC'), ('gm', 'GM')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='posted_as_type',
            field=models.CharField(blank=True, choices=[('', 'Self'), ('character', 'Character'), ('npc', 'NPC'), ('gm', 'GM')], default='', help_text='If set, the message is displayed as this dossier instead of the sender.', max_length=20),
        ),
    ]
