# Generated by Django 5.2.11 on 2026-03-30 09:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0004_add_membership_alias'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmembership',
            name='hidden',
            field=models.BooleanField(default=False, help_text='Hidden members have read-only shadow access (from Gain Access cyber action).'),
        ),
        migrations.CreateModel(
            name='CyberAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_persona_type', models.CharField(blank=True, default='', max_length=20)),
                ('actor_persona_id', models.PositiveIntegerField(blank=True, null=True)),
                ('actor_persona_name', models.CharField(blank=True, default='', max_length=200)),
                ('action_type', models.CharField(choices=[('gain_access', 'Gain Access'), ('deploy', 'Deploy'), ('defend', 'Defend'), ('detect', 'Detect')], max_length=20)),
                ('dice_pool', models.PositiveIntegerField(default=0)),
                ('dice_results', models.JSONField(default=list, help_text='List of individual d10 results.')),
                ('successes', models.IntegerField(default=0)),
                ('is_exceptional', models.BooleanField(default=False)),
                ('is_dramatic_failure', models.BooleanField(default=False)),
                ('gm_modifier', models.IntegerField(default=0, help_text='Bonus (+) or penalty (-) dice from GM.')),
                ('notes', models.TextField(blank=True, default='')),
                ('outcome', models.TextField(blank=True, default='', help_text='Description of what happened as a result.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cyber_actions_against', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_actions', to='comms.thread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ThreadEffect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('effect_type', models.CharField(choices=[('encrypted', 'Encrypted'), ('obfuscated', 'Obfuscated'), ('backdoor', 'Backdoor'), ('compromised', 'Compromised'), ('locked', 'Locked')], max_length=20)),
                ('level', models.PositiveIntegerField(default=1, help_text='Effect strength (1-3 for encryption).')),
                ('source_agency_id', models.PositiveIntegerField(blank=True, help_text='Agency that placed this effect.', null=True)),
                ('target_agency_id', models.PositiveIntegerField(blank=True, help_text='Agency targeted by this effect.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('source_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_effects', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_effects', to='comms.thread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
