# Generated by Django 5.2.11 on 2026-03-30 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0005_add_cyber_terminal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='is_connection_closed',
            field=models.BooleanField(default=False, help_text='Connection closed — no new messages or terminal actions.'),
        ),
        migrations.CreateModel(
            name='CyberSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attacker_persona_name', models.CharField(blank=True, default='', max_length=200)),
                ('gain_access_successes', models.IntegerField(default=0)),
                ('is_exceptional', models.BooleanField(default=False)),
                ('deploys_remaining', models.IntegerField(default=0)),
                ('has_backdoor', models.BooleanField(default=False, help_text='Permanent backdoor = unlimited deploys.')),
                ('detected', models.BooleanField(default=False)),
                ('last_detect_result', models.CharField(blank=True, default='', help_text="Cache: 'detected' or 'clean'. Reset on new attacker action.", max_length=50)),
                ('detect_stale', models.BooleanField(default=True, help_text='True if no new attacker action since last detect.')),
                ('difficulty_penalty', models.IntegerField(default=0, help_text='Extra difficulty on next Gain Access (+1 per prior close).')),
                ('is_active', models.BooleanField(default=True)),
                ('is_closed', models.BooleanField(default=False, help_text='Connection closed — no further actions possible.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_sessions', to=settings.AUTH_USER_MODEL)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cyber_sessions', to='comms.thread')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
