# Generated by Django 5.2.11 on 2026-03-30 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0006_add_cyber_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='posted_as_type',
            field=models.CharField(blank=True, choices=[('', 'Self'), ('character', 'Character'), ('npc', 'NPC'), ('gm', 'GM'), ('system', 'System')], default='', help_text='If set, the message is displayed as this dossier instead of the sender.', max_length=20),
        ),
        migrations.AlterField(
            model_name='threadmembership',
            name='alias_type',
            field=models.CharField(blank=True, choices=[('', 'Self'), ('character', 'Character'), ('npc', 'NPC'), ('gm', 'GM'), ('system', 'System')], default='', max_length=20),
        ),
    ]
