# Generated by Django 5.2.11 on 2026-03-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0007_add_system_posted_as_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cybersession',
            name='helper_concealment_damage',
            field=models.IntegerField(default=0, help_text="Boxes marked on helper's digital concealment track."),
        ),
        migrations.AddField(
            model_name='cybersession',
            name='helper_npc_id',
            field=models.PositiveIntegerField(blank=True, help_text='NPC dossier ID assisting the attacker.', null=True),
        ),
    ]
