# Generated by Django 5.2.11 on 2026-03-30 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0008_add_helper_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='defense_active',
            field=models.BooleanField(default=False, help_text='Whether Defend has been executed on this thread.'),
        ),
        migrations.AddField(
            model_name='thread',
            name='defense_bonus',
            field=models.IntegerField(default=0, help_text='Defense bonus from Defend action — adds to all detection rolls.'),
        ),
    ]
