# Generated by Django 5.2.11 on 2026-03-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0009_add_defense_bonus'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='intrusion_detected',
            field=models.BooleanField(default=False, help_text='Permanent flag — intrusion was detected on this thread.'),
        ),
    ]
