# Generated by Django 5.2.11 on 2026-04-07 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comms', '0010_add_intrusion_detected'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmembership',
            name='defense_active',
            field=models.BooleanField(default=False, help_text='Whether this user has activated Defend on this thread.'),
        ),
        migrations.AddField(
            model_name='threadmembership',
            name='defense_bonus',
            field=models.IntegerField(default=0, help_text='Per-user defense bonus from Defend action.'),
        ),
    ]
