# Generated by Django 5.2.11 on 2026-04-27 11:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0012_add_merit_uses'),
        ('npcs', '0009_npc_is_child_prodigy'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Encounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('active', 'Active'), ('concluded', 'Concluded')], default='setup', max_length=20)),
                ('round_number', models.IntegerField(default=0, help_text='0 in setup, 1+ once started.')),
                ('active_participant_id', models.IntegerField(blank=True, help_text='Id of the Participant whose turn it currently is.', null=True)),
                ('initiative_order', models.JSONField(blank=True, default=list, help_text='List of Participant ids in descending initiative order.')),
                ('scene_description', models.TextField(blank=True, default='')),
                ('location_text', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Free-form extension hooks (lighting, hazards, etc.).')),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_encounters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_kind', models.CharField(choices=[('character', 'Character'), ('npc', 'NPC'), ('mook', 'Mook')], max_length=10)),
                ('name', models.CharField(help_text='Display name; copied from character/npc, or free-form for mooks.', max_length=200)),
                ('faction', models.CharField(choices=[('player', 'Player'), ('ally', 'Ally'), ('hostile', 'Hostile'), ('neutral', 'Neutral')], default='hostile', max_length=20)),
                ('initiative_score', models.IntegerField(blank=True, help_text='Composite tiebreak key for sort order in the round.', null=True)),
                ('initiative_roll', models.IntegerField(blank=True, help_text='Raw success count from the initiative roll.', null=True)),
                ('health_bashing', models.IntegerField(default=0)),
                ('health_lethal', models.IntegerField(default=0)),
                ('health_aggravated', models.IntegerField(default=0)),
                ('health_max', models.IntegerField(default=7)),
                ('willpower_current', models.IntegerField(default=0)),
                ('willpower_max', models.IntegerField(default=0)),
                ('mental_load', models.IntegerField(default=0)),
                ('defense_override', models.IntegerField(blank=True, help_text='Pinned defense value; null = compute from underlying sheet.', null=True)),
                ('cover_state', models.CharField(choices=[('none', 'None'), ('light', 'Light'), ('heavy', 'Heavy'), ('full', 'Full')], default='none', max_length=20)),
                ('cover_entry_name', models.CharField(blank=True, default='', help_text='SiteSettings.cover entry name backing the current cover state.', max_length=120)),
                ('cover_durability', models.IntegerField(blank=True, null=True)),
                ('cover_health', models.IntegerField(blank=True, null=True)),
                ('weapon_name', models.CharField(blank=True, default='', max_length=120)),
                ('weapon_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of the weapon stat block at the time of equipping.')),
                ('armor_name', models.CharField(blank=True, default='', max_length=120)),
                ('armor_data', models.JSONField(blank=True, default=dict, help_text='Snapshot of the armor stat block at the time of equipping.')),
                ('conditions', models.JSONField(blank=True, default=list, help_text='List of active condition tags (prone, stunned, blinded, ...).')),
                ('position_label', models.CharField(default='engaged', max_length=40)),
                ('position_order', models.IntegerField(default=0)),
                ('notes', models.TextField(blank=True, default='')),
                ('mook_combat_pool', models.IntegerField(blank=True, null=True)),
                ('mook_defense', models.IntegerField(blank=True, null=True)),
                ('mook_armor_rating', models.CharField(blank=True, default='', max_length=20)),
                ('surprise_immune', models.BooleanField(default=False)),
                ('acted_this_round', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_participations', to='characters.character')),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='combat.encounter')),
                ('npc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='combat_participations', to='npcs.npc')),
            ],
            options={
                'ordering': ['encounter', 'position_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CombatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField(help_text='Monotonic per encounter; unique with (encounter, sequence).')),
                ('round_number', models.IntegerField(default=0)),
                ('action_type', models.CharField(help_text='Free-form in Phase 0; vocabulary: system, note, initiative, turn_advance, round_advance, attack, move, ability, condition_set, condition_clear, health_change, willpower_change, cover_change, weapon_change, armor_change, rollback.', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Action-specific payload (rolls, deltas, before/after snapshots).')),
                ('message', models.TextField(blank=True, default='')),
                ('is_reverted', models.BooleanField(default=False, help_text='Reserved for the rollback handler in a later phase.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('encounter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_entries', to='combat.encounter')),
                ('actor_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actor_log_entries', to='combat.participant')),
                ('target_participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_log_entries', to='combat.participant')),
            ],
            options={
                'ordering': ['encounter', 'sequence', 'id'],
                'constraints': [models.UniqueConstraint(fields=('encounter', 'sequence'), name='combat_combatlog_unique_seq')],
            },
        ),
    ]
