# Generated by Django 5.2.11 on 2026-04-27 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0001_initial'),
        ('gm_workspace', '0002_timeline_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='story_idea',
            field=models.ForeignKey(blank=True, help_text='Optional link to the story arc this combat belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='encounters', to='gm_workspace.storyidea'),
        ),
    ]
