# Generated by Django 5.2.11 on 2026-04-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0002_encounter_story_idea'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='offhand_weapon_data',
            field=models.JSONField(blank=True, default=dict, help_text='Snapshot of the off-hand weapon stat block at the time of equipping.'),
        ),
        migrations.AddField(
            model_name='participant',
            name='offhand_weapon_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
