# Generated by Django 5.2.11 on 2026-04-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('combat', '0003_participant_offhand'),
    ]

    operations = [
        migrations.AddField(
            model_name='encounter',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text="If True, the encounter is GM-prep only — players don't see it in their list, can't access the detail page, and the WS consumer rejects their subscription. Toggle visibility via the RELEASE / HIDE button on the encounter detail page."),
        ),
    ]
