# Generated by Django 5.2.11 on 2026-03-16 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0007_council_membership'),
        ('npcs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='agency',
            field=models.ForeignKey(blank=True, help_text='The NPC agency this dossier belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='npc_dossiers', to='agencies.agency'),
        ),
        migrations.AddField(
            model_name='npc',
            name='is_npc_dossier',
            field=models.BooleanField(default=False, help_text='NPC dossiers are admin-managed and linked to NPC agencies.'),
        ),
        migrations.AlterField(
            model_name='npc',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_npcs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='NPCNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc_notes', to=settings.AUTH_USER_MODEL)),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='npcs.npc')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
