# Generated by Django 5.2.11 on 2026-03-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0002_npc_agency_npc_is_npc_dossier_alter_npc_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Hidden dossiers are only visible to superusers.'),
        ),
    ]
