# Generated by Django 5.2.11 on 2026-03-25 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0004_add_stats_to_npc'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='character_class',
            field=models.CharField(blank=True, choices=[('fixer', 'Fixer'), ('soldier', 'Soldier'), ('science', 'Science'), ('engineer', 'Engineer'), ('ai', 'AI')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='npc',
            name='class_classified',
            field=models.BooleanField(default=False, help_text='If true, the class is shown as CLASSIFIED to non-superusers.'),
        ),
    ]
