# Generated by Django 5.2.11 on 2026-03-28 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exodus', '0009_meritdefinition_class_restriction'),
        ('npcs', '0005_npc_character_class_npc_class_classified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='npc',
            name='merits',
            field=models.JSONField(db_column='merits', default=list),
        ),
        migrations.RenameField(
            model_name='npc',
            old_name='merits',
            new_name='merits_old',
        ),
        migrations.CreateModel(
            name='NpcMerit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=1)),
                ('merit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exodus.meritdefinition')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc_merits', to='npcs.npc')),
            ],
            options={
                'ordering': ['merit__category', 'merit__name'],
            },
        ),
        migrations.AddField(
            model_name='npc',
            name='merit_entries',
            field=models.ManyToManyField(blank=True, through='npcs.NpcMerit', to='exodus.meritdefinition'),
        ),
        migrations.CreateModel(
            name='NpcPullingString',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('npc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='npc_pulling_strings', to='npcs.npc')),
                ('pulling_string', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exodus.pullingstring')),
            ],
            options={
                'ordering': ['pulling_string__category', 'pulling_string__name'],
            },
        ),
        migrations.AddField(
            model_name='npc',
            name='pulling_strings',
            field=models.ManyToManyField(blank=True, through='npcs.NpcPullingString', to='exodus.pullingstring'),
        ),
    ]
