# Generated by Django 5.2.11 on 2026-03-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0006_alter_npc_merits_rename_merits_npc_merits_old_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='experience_used',
            field=models.IntegerField(default=0),
        ),
    ]
