# Generated by Django 5.2.11 on 2026-03-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0007_npc_experience_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='detected_by_agency',
            field=models.CharField(blank=True, default='', help_text='Agency that detected this NPC during cyber operations. Set when compromised.', max_length=200),
        ),
        migrations.AlterField(
            model_name='npc',
            name='state',
            field=models.CharField(choices=[('active', 'Active'), ('leave', 'Leave'), ('medical_leave', 'Medical Leave'), ('missing', 'Missing'), ('compromised', 'Compromised — Underground'), ('deceased', 'Deceased')], default='active', max_length=20),
        ),
    ]
