# Generated by Django 5.2.11 on 2026-04-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('npcs', '0009_npc_is_child_prodigy'),
    ]

    operations = [
        migrations.AddField(
            model_name='npc',
            name='merit_uses',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
