# Generated by Django 5.2.11 on 2026-04-11 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agencies', '0033_councilitem_predicted_votes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_level', models.IntegerField(default=0, help_text='0=none, 1=survey, 2=focused, 3=deep.')),
                ('scanned_resources', models.JSONField(default=dict, help_text='Resources with uncertainty applied based on scan level.')),
                ('current_successes', models.IntegerField(default=0, help_text='Accumulated successes toward next scan level.')),
                ('required_successes', models.IntegerField(default=3, help_text='Successes needed for next level (3/5/8).')),
                ('player', models.CharField(blank=True, default='', max_length=200)),
                ('base_id', models.IntegerField(blank=True, null=True)),
                ('base_name', models.CharField(blank=True, default='', max_length=200)),
                ('metadata', models.JSONField(default=dict)),
                ('scanned_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_scans', to='agencies.agency')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanRollLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('star_system_name', models.CharField(max_length=200)),
                ('character_name', models.CharField(max_length=200)),
                ('roll_type', models.CharField(max_length=20)),
                ('pool', models.IntegerField()),
                ('rolls', models.JSONField(default=list)),
                ('successes', models.IntegerField(default=0)),
                ('old_level', models.IntegerField(default=0)),
                ('new_level', models.IntegerField(default=0)),
                ('message', models.TextField(blank=True, default='')),
                ('rolled_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_roll_logs', to='agencies.agency')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roll_logs', to='starmap.agencyscan')),
            ],
            options={
                'ordering': ['-rolled_at'],
            },
        ),
        migrations.CreateModel(
            name='StarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('x', models.FloatField(help_text='3D x-coordinate in light-years, Sol at origin.')),
                ('y', models.FloatField(help_text='3D y-coordinate in light-years.')),
                ('z', models.FloatField(help_text='3D z-coordinate in light-years.')),
                ('distance', models.FloatField(help_text='Distance from Sol in light-years.')),
                ('spectral_type', models.CharField(max_length=20)),
                ('planets', models.IntegerField(default=0)),
                ('is_sol', models.BooleanField(default=False)),
                ('is_endgame', models.BooleanField(default=False, help_text='Visible but unreachable beacon system.')),
                ('resources', models.JSONField(default=dict, help_text='{"ice": 0-100, "metals": ..., "rareEarth": ..., "helium3": ..., "hydrocarbons": ..., "exotic": ...}')),
                ('scan_level_truth', models.IntegerField(default=0, help_text="GM's true scan level. 0=unscanned, 1=survey, 2=focused, 3=deep.")),
                ('claimed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('claimed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='claimed_systems', to='agencies.agency')),
            ],
            options={
                'ordering': ['distance', 'name'],
            },
        ),
        migrations.AddField(
            model_name='agencyscan',
            name='star_system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agency_scans', to='starmap.starsystem'),
        ),
        migrations.AlterUniqueTogether(
            name='agencyscan',
            unique_together={('agency', 'star_system')},
        ),
    ]
