# Generated by Django 5.2.11 on 2026-04-11 16:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starmap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('search_query', models.CharField(blank=True, default='', max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('zoom', models.IntegerField(default=13)),
                ('enabled', models.BooleanField(default=True)),
                ('visible_to_players', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityMapMarker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('marker_type', models.CharField(choices=[('base', 'Base'), ('mission', 'Mission'), ('npc', 'NPC'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('color', models.CharField(default='#00ff88', max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('visible_to_players', models.BooleanField(default=True)),
                ('linked_base_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('city_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='starmap.citymap')),
            ],
            options={
                'ordering': ['label'],
            },
        ),
    ]
