# Generated by Django 5.2.11 on 2026-04-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starmap', '0002_citymap_citymapmarker'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymapmarker',
            name='linked_character_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='citymapmarker',
            name='portrait_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='citymapmarker',
            name='marker_type',
            field=models.CharField(choices=[('base', 'Base'), ('mission', 'Mission'), ('npc', 'NPC'), ('player', 'Player'), ('custom', 'Custom')], default='custom', max_length=20),
        ),
    ]
