# Generated by Django 5.2.11 on 2026-04-11 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0033_councilitem_predicted_votes'),
        ('starmap', '0003_citymapmarker_linked_character_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Civilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('tech_level', models.CharField(choices=[('type_0', 'Type 0 — Sub-planetary'), ('type_i', 'Type I — Planetary'), ('type_ii', 'Type II — Stellar'), ('type_iii', 'Type III — Galactic')], default='type_0', max_length=20)),
                ('disposition', models.CharField(choices=[('unknown', 'Unknown'), ('friendly', 'Friendly'), ('neutral', 'Neutral'), ('cautious', 'Cautious'), ('hostile', 'Hostile')], default='unknown', max_length=50)),
                ('portrait_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_hidden', models.BooleanField(default=True, help_text='Hidden from players until revealed.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(default='#00ff88', max_length=20)),
                ('icon', models.CharField(blank=True, default='', max_length=10)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StarSystemCivilisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('population_estimate', models.CharField(blank=True, default='', max_length=100)),
                ('notes', models.TextField(blank=True, default='')),
                ('discovered', models.BooleanField(default=False)),
                ('scan_level_required', models.IntegerField(default=2, help_text='Minimum scan level to discover this civilisation.')),
                ('civilisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='star_systems', to='starmap.civilisation')),
                ('discovered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_civilisations', to='agencies.agency')),
                ('star_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='civilisations', to='starmap.starsystem')),
            ],
            options={
                'unique_together': {('star_system', 'civilisation')},
            },
        ),
    ]
