# Generated by Django 5.2.11 on 2026-04-11 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0033_councilitem_predicted_votes'),
        ('starmap', '0004_civilisation_resourcetype_starsystemcivilisation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="e.g. 'Proxima b', 'Tau Ceti e'", max_length=200)),
                ('orbital_position', models.IntegerField(default=1, help_text='Position from star (1 = closest)')),
                ('planet_type', models.CharField(default='terrestrial', help_text='e.g. terrestrial, gas_giant, ice_giant, dwarf, ocean_world', max_length=50)),
                ('atmosphere', models.CharField(choices=[('none', 'None'), ('oxygen', 'Oxygen-based'), ('methane', 'Methane-based'), ('argon', 'Argon-based'), ('nitrogen', 'Nitrogen-based'), ('co2', 'Carbon Dioxide'), ('hydrogen', 'Hydrogen-Helium'), ('ammonia', 'Ammonia'), ('toxic', 'Toxic Mix'), ('unknown', 'Unknown')], default='unknown', max_length=20)),
                ('atmosphere_details', models.CharField(blank=True, default='', help_text="Custom atmosphere composition, e.g. '78% N2, 21% O2, 1% Ar'", max_length=200)),
                ('life_type', models.CharField(choices=[('none', 'No Life Detected'), ('prebiotic', 'Prebiotic Chemistry'), ('bacterial', 'Bacterial / Microbial'), ('cellular', 'Cellular Organisms'), ('plant', 'Plant Life'), ('animal', 'Animal Life'), ('intelligent', 'Intelligent Life'), ('unknown', 'Unknown')], default='none', max_length=20)),
                ('life_details', models.TextField(blank=True, default='', help_text='Description of detected life (markdown).')),
                ('temperature_range', models.CharField(blank=True, default='', help_text="e.g. '-20°C to 45°C'", max_length=100)),
                ('gravity', models.CharField(blank=True, default='', help_text="e.g. '0.9g', '1.2g'", max_length=50)),
                ('water', models.BooleanField(default=False, help_text='Liquid water detected')),
                ('habitable', models.BooleanField(default=False, help_text='In the habitable zone')),
                ('resources', models.JSONField(blank=True, default=dict, help_text='Planet-specific resources (override star system defaults).')),
                ('notes', models.TextField(blank=True, default='')),
                ('is_hidden', models.BooleanField(default=True, help_text='Hidden from players until revealed.')),
                ('scan_level_required', models.IntegerField(default=1, help_text='Minimum scan level to discover this planet.')),
                ('discovered', models.BooleanField(default=False)),
                ('discovered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discovered_planets', to='agencies.agency')),
                ('star_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets_of_interest', to='starmap.starsystem')),
            ],
            options={
                'ordering': ['star_system', 'orbital_position'],
            },
        ),
    ]
