# Generated by Django 5.2.11 on 2026-06-20 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starmap', '0007_seed_resource_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='starsystem',
            name='difficulty_mod',
            field=models.IntegerField(default=0, help_text='Scan difficulty modifier -10..+10. Target successes = 15 + this (clamped 5..25).'),
        ),
        migrations.AddField(
            model_name='starsystem',
            name='discovered',
            field=models.BooleanField(default=False, help_text='GM gate: a system must be discovered before agencies can scan or retrieve data.'),
        ),
        migrations.AddField(
            model_name='starsystem',
            name='has_livable_planet',
            field=models.BooleanField(default=False, help_text='Single truth: does this system have a livable planet? Scanning approximates it.'),
        ),
        migrations.AlterField(
            model_name='starsystem',
            name='scan_level_truth',
            field=models.IntegerField(default=0, help_text='Vestigial (legacy scan-level system). Superseded by the uncertainty model.'),
        ),
    ]
