# Generated by Django 5.2.11 on 2026-06-20 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0037_agency_scan_turn_usage'),
        ('starmap', '0008_starsystem_difficulty_mod_starsystem_discovered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_false', models.BooleanField(default=False, help_text="Disinformation (GM-only). Raises the system's scan difficulty.")),
                ('uncertainty', models.IntegerField(default=100, help_text='Stated uncertainty% of the published data (faked for false records).')),
                ('payload', models.JSONField(default=dict, help_text='Published approximate readout snapshot {resources, livable}.')),
                ('published_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_scan_records', to='agencies.agency')),
                ('star_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_records', to='starmap.starsystem')),
            ],
            options={
                'ordering': ['star_system', 'agency'],
                'unique_together': {('agency', 'star_system')},
            },
        ),
    ]
